# Config file for automatic testing at travis-ci.org

language: python

python: 3.5

sudo: false

env:
  matrix:
    - TOXENV=pep8
    - TOXENV=isort
    - TOXENV=py35-dj19-cms33
    - TOXENV=py35-dj19-cms32
    - TOXENV=py34-dj19-cms33
    - TOXENV=py34-dj19-cms32
    - TOXENV=py27-dj19-cms33
    - TOXENV=py27-dj19-cms32
    - TOXENV=py35-dj18-cms33
    - TOXENV=py35-dj18-cms32
    - TOXENV=py35-dj18-cms31
    - TOXENV=py34-dj18-cms33
    - TOXENV=py34-dj18-cms32
    - TOXENV=py34-dj18-cms31
    - TOXENV=py33-dj18-cms33
    - TOXENV=py33-dj18-cms32
    - TOXENV=py33-dj18-cms31
    - TOXENV=py27-dj18-cms33
    - TOXENV=py27-dj18-cms32
    - TOXENV=py27-dj18-cms31

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox>=1.8 coveralls

# command to run tests, e.g. python setup.py test
script: COMMAND='coverage run' tox -e$TOXENV

after_success: coveralls
